/*
 * CadastroUsuario.java
 *
 * Created on 9 de Setembro de 2005, 01:11
 */

package siscorpi.gui;
import  siscorpi.util.*;
import  javax.swing.*;
import  java.sql.*;
import  siscorpi.usuario.*;
import  siscorpi.pedido.*;

/**
 *
 * @author  sergio
 */
public class CadastroUsuario extends javax.swing.JFrame {
    private Pedido fachada;
    private Usuario usuarioSelecionado;
    
    /** Creates new form CadastroUsuario */
    public CadastroUsuario() {
        try {
            this.fachada = new Pedido();
            initComponents(); 
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCorpI");
        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setText("Login:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 50, 14);

        tfLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLoginFocusLost(evt);
            }
        });

        jPanel2.add(tfLogin);
        tfLogin.setBounds(70, 20, 110, 19);

        jLabel2.setText("Senha:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 20, 50, 14);

        tfSenha.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11));
        tfSenha.setPreferredSize(new java.awt.Dimension(62, 19));
        jPanel2.add(tfSenha);
        tfSenha.setBounds(250, 20, 100, 20);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Cadastro de Usu\u00e1rios");
        jPanel1.add(jLabel17);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jPanel3.add(btGravar);

        btExcluir.setMnemonic('x');
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jPanel3.add(btExcluir);

        btCancelar.setMnemonic('C');
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel3.add(btCancelar);

        btPesquisar.setMnemonic('P');
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jPanel3.add(btPesquisar);

        btSair.setMnemonic('r');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel3.add(btSair);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void tfLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoginFocusLost
        // TODO add your handling code here:
        String login = tfLogin.getText();
        if (login.equals("")) {
            resetUsuario();
        } else {
            try {
                this.usuarioSelecionado = fachada.procurarUsuario(login);
                atualizaCampos();
            } catch(UsuarioNaoEncontradoException ex){
                resetUsuario();
                tfLogin.setText(login);
            } catch(RepositorioException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
                JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfLoginFocusLost

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        resetUsuario();
        tfLogin.requestFocus();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        String login = tfLogin.getText();
        try {
            fachada.removerUsuario(login);
            resetUsuario();
            JOptionPane.showMessageDialog(null,"Usuário excluído com êxito...",
            "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
        } catch(UsuarioNaoEncontradoException ex){
            resetUsuario();
            tfLogin.setText(login);
        } catch(RepositorioException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        try {
            if (criaUsuario()) {
                fachada.cadastrarUsuario(usuarioSelecionado);
                JOptionPane.showMessageDialog(null,"Gravação realizada com êxito...",
                "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(UsuarioNaoEncontradoException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } catch(RepositorioException ex){ 
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private boolean criaUsuario() {
        boolean resposta = false;
        String login     = tfLogin.getText();
        String senha     = tfSenha.getText();
        if (login.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o login de usuário","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (senha.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite a senha","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (usuarioSelecionado == null) {
            usuarioSelecionado = new Usuario(login,senha);
            resposta = true;
        } else {
            usuarioSelecionado.setSenha(senha);
            resposta = true;
        }
        return resposta;
    }
    /**
    * Inicia os componentes sem conteúdo na tela de cadastro
    * 
    */    
    private void resetUsuario() {
        usuarioSelecionado = null;
        tfLogin.setText("");
        tfSenha.setText("");
    }
    /**
    * Atualiza os dados na tela do registro em um banco de dados SQL
    * 
    */    
    private void atualizaCampos()
    {
        if (usuarioSelecionado != null) {
            tfLogin.setText(usuarioSelecionado.getLogin());
            tfSenha.setText(usuarioSelecionado.getSenha());
        }
    } 
    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        tfLogin.requestFocus();
        PesqQuery pesq_usu = new PesqQuery(5, 
        "SELECT LOGIN FROM USUARIO WHERE ",
        new String [] {"Login"},new String [] {"LOGIN"},0,                
        new java.awt.Frame(), true);
	pesq_usu.setVisible(true);
        if ( pesq_usu.getReturnStatus() == 1 )
        {
            tfLogin.setText(pesq_usu.toString());
            tfSenha.requestFocus();
        }    
        pesq_usu = null;
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
    
}
