/*
 * CadastroCliente.java
 *
 * Criado em 4 de Abril de 2005, 22:36
 */
package siscorpi.gui;
import  siscorpi.util.*;
import  javax.swing.*;
import  java.sql.*;
import  siscorpi.cliente_fornecedor.*;
import  siscorpi.pedido.*;

/**
 * A classe CadastroCliente é responsável pela manutenção da base de dados
 * do cliente 
 *
 * @author Sérgio Leite Bruno
 * @version 1.0
 */
public class CadastroCliente extends javax.swing.JFrame{
    private Pedido fachada;
    private Cliente_fornecedor clienteSelecionado;
    ClasseRemoveCaracteres cRemoveCaracteres = new ClasseRemoveCaracteres();
    ClasseMascaraCnpjCPF   cMascaraCnpjCPF   = new ClasseMascaraCnpjCPF();    
    ClasseTestaCodigoVazio cTestaCodigoVazio = new ClasseTestaCodigoVazio();    
    
    /**
    * Realiza alteração do registro em um banco de dados SQL
    */    
    public CadastroCliente() 
    { 
        try {
            this.fachada = new Pedido();
            initComponents(); 
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfRazao_social = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfFantasia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfFone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfFax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfCelular = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfEstado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfCep = new javax.swing.JFormattedTextField();
        btUf = new javax.swing.JButton();
        tfCnpj_cpf = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisCorpI");
        setFocusCycleRoot(false);
        setFont(new java.awt.Font("[.sickness.]", 0, 10));
        setForeground(java.awt.Color.white);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName(null);
        setResizable(false);
        jLabel1.setText("C\u00f3digo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 50, 20);

        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFocusLost(evt);
            }
        });

        getContentPane().add(tfCodigo);
        tfCodigo.setBounds(90, 30, 60, 19);

        jLabel2.setText("CNPJ/CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 30, 70, 20);

        jLabel3.setText("IE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 30, 50, 20);

        tfIe.setName("tfIe");
        getContentPane().add(tfIe);
        tfIe.setBounds(400, 30, 150, 19);

        jLabel4.setText("Raz\u00e3o Social:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 60, 80, 20);

        tfRazao_social.setName("tfRazao_social");
        getContentPane().add(tfRazao_social);
        tfRazao_social.setBounds(90, 60, 460, 19);

        jLabel5.setText("Fantasia:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 90, 80, 20);

        tfFantasia.setName("tfFantasia");
        getContentPane().add(tfFantasia);
        tfFantasia.setBounds(90, 90, 270, 19);

        jLabel6.setText("Endere\u00e7o:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 120, 80, 20);

        tfEndereco.setName("tfEndereco");
        getContentPane().add(tfEndereco);
        tfEndereco.setBounds(90, 120, 460, 19);

        jLabel7.setText("N\u00famero:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 150, 50, 20);

        tfNumero.setName("tfNumero");
        getContentPane().add(tfNumero);
        tfNumero.setBounds(90, 150, 60, 19);

        jLabel8.setText("Bairro:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 150, 50, 20);

        tfBairro.setName("tfBairro");
        getContentPane().add(tfBairro);
        tfBairro.setBounds(200, 150, 350, 19);

        jLabel9.setText("Cidade:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 180, 50, 20);

        tfCidade.setName("tfCidade");
        getContentPane().add(tfCidade);
        tfCidade.setBounds(90, 180, 240, 19);

        jLabel10.setText("CEP:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 180, 40, 20);

        jLabel11.setText("Telefone:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 210, 70, 20);

        getContentPane().add(tfFone);
        tfFone.setBounds(90, 210, 100, 19);

        jLabel12.setText("Fax:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(200, 210, 30, 20);

        getContentPane().add(tfFax);
        tfFax.setBounds(230, 210, 100, 19);

        jLabel13.setText("Celular:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 210, 60, 20);

        getContentPane().add(tfCelular);
        tfCelular.setBounds(390, 210, 160, 19);

        jLabel14.setText("E-mail:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 240, 80, 20);

        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });

        getContentPane().add(tfEmail);
        tfEmail.setBounds(90, 240, 460, 19);

        jLabel15.setText("UF:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(470, 180, 30, 20);

        tfEstado.setName("tfCep");
        getContentPane().add(tfEstado);
        tfEstado.setBounds(490, 180, 30, 20);

        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Cadastro de Clientes");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(230, 0, 150, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 20);

        getContentPane().add(tfCep);
        tfCep.setBounds(390, 180, 70, 21);

        btUf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pesquisar.GIF")));
        btUf.setFocusPainted(false);
        btUf.setOpaque(false);
        btUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUfActionPerformed(evt);
            }
        });

        getContentPane().add(btUf);
        btUf.setBounds(520, 180, 30, 20);

        tfCnpj_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCnpj_cpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCnpj_cpfFocusLost(evt);
            }
        });

        getContentPane().add(tfCnpj_cpf);
        tfCnpj_cpf.setBounds(230, 30, 130, 21);

        jLabel17.setText("Tipo:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 90, 30, 20);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Fornecedor", "Ambos" }));
        getContentPane().add(cbTipo);
        cbTipo.setBounds(400, 90, 150, 22);

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.setPreferredSize(new java.awt.Dimension(73, 26));
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jPanel1.add(btGravar);

        btExcluir.setMnemonic('x');
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(75, 26));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jPanel1.add(btExcluir);

        btCancelar.setMnemonic('C');
        btCancelar.setText("Cancelar");
        btCancelar.setPreferredSize(new java.awt.Dimension(85, 26));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel1.add(btCancelar);

        btPesquisar.setMnemonic('P');
        btPesquisar.setText("Pesquisar");
        btPesquisar.setPreferredSize(new java.awt.Dimension(95, 26));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jPanel1.add(btPesquisar);

        btSair.setMnemonic('r');
        btSair.setText("Sair");
        btSair.setPreferredSize(new java.awt.Dimension(65, 26));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel1.add(btSair);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 270, 560, 45);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    /**
    * Validar o e-mail caso seja preenchido verifica a existência da @
    * 
    */    
    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        // TODO add your handling code here:
        if ( ! tfEmail.getText().equals("") && tfEmail.getText().indexOf("@") == -1 )
        {
            JOptionPane.showMessageDialog( null, "E-mail informado inválido verifique a existência de '@'",
            "SisCorpI - Informação",JOptionPane.INFORMATION_MESSAGE );
            tfEmail.requestFocus();
        }    
    }//GEN-LAST:event_tfEmailFocusLost
    /**
    * Limpar a máscara do CNPJ ou CPF
    * 
    */    
    private void tfCnpj_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCnpj_cpfFocusGained
        // TODO add your handling code here:
        tfCnpj_cpf.setText( cRemoveCaracteres.RemoveCaracteres( new String("./-"), tfCnpj_cpf.getText() ) );
    }//GEN-LAST:event_tfCnpj_cpfFocusGained
    /**
    * Ao perder o foco o sistema verifica a consistência do CPF ou CNPJ
    * 
    */    
    private void tfCnpj_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCnpj_cpfFocusLost
        // TODO add your handling code here:
        boolean validou = false, wECpf = false;
        String wVal;
        wVal = tfCnpj_cpf.getText().trim();
        if ( wVal.length() == 11 )
        {
            wECpf = true;
            ClasseValidaCpf cValidaCpf = new ClasseValidaCpf();
            if ( ! cValidaCpf.ValidaCpf( tfCnpj_cpf.getText() ) )
            {    
                JOptionPane.showMessageDialog( null, "CPF informado inválido ",
                "SisCorpI - Informação",
                JOptionPane.INFORMATION_MESSAGE );
                //tfCnpj_cpf.requestFocus();
            }
            else validou = true; 
            cValidaCpf = null;
        }
        else
        {
            ClasseValidaCnpj cValidaCnpj = new ClasseValidaCnpj();
            if ( ! cValidaCnpj.ValidaCnpj( tfCnpj_cpf.getText() ) )
            {    
                JOptionPane.showMessageDialog( null, "CNPJ informado inválido ",
                "SisCorpI - Informação",
                JOptionPane.INFORMATION_MESSAGE );
                //tfCnpj_cpf.requestFocus();
            }
            else validou = true; 
            cValidaCnpj = null;
        }    
        if ( validou )
        {
            // VERIFICAR SE ESTE CPF OU CNPJ PERTENCE A OUTRO CLIENTE
        }
        tfCnpj_cpf.setText( cMascaraCnpjCPF.MascaraCnpjCPF( tfCnpj_cpf.getText() ) );
    }//GEN-LAST:event_tfCnpj_cpfFocusLost
    /**
    * Realiza consulta dos registros de UF em um banco de dados SQL
    * 
    */    
    private void btUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUfActionPerformed
        // TODO add your handling code here:
        /*
        tfEstado.requestFocus();
        PesqQuery pesq_cli = new PesqQuery("SELECT * FROM uf where ",
        new String [] {"Sigla","Estado"},new String [] {"Sigla","Descricao"},1,
        new java.awt.Frame(), true);
	pesq_cli.setVisible(true);
        if ( pesq_cli.getReturnStatus() == 1 )
        {
            tfEstado.setText(pesq_cli.toString());
            tfFone.requestFocus();
        }    
        pesq_cli = null;
         */
    }//GEN-LAST:event_btUfActionPerformed
    /**
    * Realiza consulta em um banco de dados SQL
    * 
    */    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        tfCodigo.requestFocus();
        PesqQuery pesq_cli = new PesqQuery(2,
        "SELECT Codigo,Cnpj_cpf,Razao_social FROM Clientes where ",
        new String [] {"Código","CNPJ/CPF","Razão Social"},
        new String [] {"Codigo","Cnpj_cpf","Razao_social"},2,                
        new java.awt.Frame(), true);
	pesq_cli.setVisible(true);
        if ( pesq_cli.getReturnStatus() == 1 )
        {
            tfCodigo.setText(pesq_cli.toString());
            tfCnpj_cpf.requestFocus();
        }    
        pesq_cli = null;
    }//GEN-LAST:event_btPesquisarActionPerformed
    /**
    * Realiza alteração ou inclusão do registro em um banco de dados SQL
    * 
    */    
    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        try {
            if (criaCliente()) {
                fachada.cadastrarCliente(clienteSelecionado);
                JOptionPane.showMessageDialog(null,"Gravação realizada com êxito...",
                "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(Cliente_fornecedorNaoEncontradoException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } catch(RepositorioException ex){ 
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btGravarActionPerformed
   
    private boolean criaCliente() {
        boolean resposta    = false;
        String codigo       = tfCodigo.getText();
        String razao_social = tfRazao_social.getText();
        String fantasia     = tfFantasia.getText();
        String cnpj_cpf     = cRemoveCaracteres.RemoveCaracteres(new String(
                              "./-"),tfCnpj_cpf.getText());
        String ie           = tfIe.getText();
        String endereco     = tfEndereco.getText();
        String bairro       = tfBairro.getText();
        String cidade       = tfCidade.getText();
        String estado       = tfEstado.getText();
        String cep          = tfCep.getText();
        String numero       = tfNumero.getText();
        String fone         = tfFone.getText();
        String fax          = tfFax.getText();
        String celular      = tfCelular.getText();
        String email        = tfEmail.getText();
        Integer tipo        = cbTipo.getSelectedIndex();
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o código do cliente","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (cnpj_cpf.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o CNPJ/CPF do cliente","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (razao_social.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite a razão social do cliente","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (clienteSelecionado == null) {
            clienteSelecionado = new Cliente_fornecedor(codigo,razao_social,
                                 fantasia,cnpj_cpf,ie,endereco,bairro,cidade, 
                                 estado,cep,numero,fone,fax,celular,email,tipo);
            resposta = true;
        } else {
            clienteSelecionado.setRazao_social(razao_social);
            clienteSelecionado.setFantasia(fantasia);
            clienteSelecionado.setCnpj_cpf(cnpj_cpf);
            clienteSelecionado.setIe(ie);
            clienteSelecionado.setEndereco(endereco);
            clienteSelecionado.setBairro(bairro);
            clienteSelecionado.setCidade(cidade); 
            clienteSelecionado.setEstado(estado);
            clienteSelecionado.setCep(cep);
            clienteSelecionado.setNumero(numero);
            clienteSelecionado.setFone(fone);
            clienteSelecionado.setFax(fax);
            clienteSelecionado.setCelular(celular);
            clienteSelecionado.setEmail(email);
            clienteSelecionado.setTipo(tipo);
            resposta = true;
        }
        return resposta;
    }
    /**
    * Inicia os componentes sem conteúdo na tela de cadastro
    * 
    */    
    void resetCliente() {
        clienteSelecionado = null;
        tfCodigo.setText("");
        tfRazao_social.setText("");
        tfFantasia.setText("");
        tfCnpj_cpf.setText("");
        tfIe.setText("");
        tfEndereco.setText("");
        tfBairro.setText("");
        tfCidade.setText("");
        tfEstado.setText("");
        tfCep.setText("");
        tfNumero.setText("");
        tfFone.setText("");
        tfFax.setText("");
        tfCelular.setText("");
        tfEmail.setText("");
        cbTipo.setSelectedIndex(0);
    }
    /**
    * Atualiza os dados na tela do registro em um banco de dados SQL
    * 
    */    
    private void atualizaCampos()
    {
        if (clienteSelecionado != null) {
            tfCodigo.setText(clienteSelecionado.getCodigo());
            tfRazao_social.setText(clienteSelecionado.getRazao_social());
            tfFantasia.setText(clienteSelecionado.getFantasia());
            tfCnpj_cpf.setText( cMascaraCnpjCPF.MascaraCnpjCPF( clienteSelecionado.getCnpj_cpf() ) );
            tfIe.setText(clienteSelecionado.getIe());
            tfEndereco.setText(clienteSelecionado.getEndereco());
            tfBairro.setText(clienteSelecionado.getBairro());
            tfCidade.setText(clienteSelecionado.getCidade());
            tfEstado.setText(clienteSelecionado.getEstado());      
            tfCep.setText(clienteSelecionado.getCep());
            tfNumero.setText(clienteSelecionado.getNumero());
            tfFone.setText(clienteSelecionado.getFone());
            tfFax.setText(clienteSelecionado.getFax());
            tfCelular.setText(clienteSelecionado.getCelular());
            tfEmail.setText(clienteSelecionado.getEmail());
            cbTipo.setSelectedIndex( clienteSelecionado.getTipo() );
        }
    } 
    /**
    * Realizar exclusão em um banco de dados SQL
    * 
    */    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        String codigo = tfCodigo.getText();
        try {
            fachada.removerCliente(codigo);
            resetCliente();
            JOptionPane.showMessageDialog(null,"Cliente excluído com êxito...",
            "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
        } catch(Cliente_fornecedorNaoEncontradoException ex){
            resetCliente();
            tfCodigo.setText(codigo);
        } catch(RepositorioException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed
    /**
    * Limpar os componentes da tela
    * 
    */    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        resetCliente();
        tfCodigo.requestFocus();
    }//GEN-LAST:event_btCancelarActionPerformed
    /**
    * Ao perder o foco o sistema verifica se existe um cadastro com este código 
    * caso exista mostra os dados caso não inicia o cadastro
    * 
    */    
    private void tfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusLost
        String codigo = tfCodigo.getText();
        if (codigo.equals("")) {
            resetCliente();
        } else {
            try {
                this.clienteSelecionado = fachada.procurarCliente(codigo);
                atualizaCampos();
            } catch(Cliente_fornecedorNaoEncontradoException ex){
                resetCliente();
                tfCodigo.setText(codigo);
            } catch(RepositorioException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
                JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfCodigoFocusLost
    /**
    * Fechar a tela de cadastro
    * 
    */    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed
   /**
   * @param args the command line arguments
   */
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btUf;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfCnpj_cpf;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfFantasia;
    private javax.swing.JTextField tfFax;
    private javax.swing.JTextField tfFone;
    private javax.swing.JTextField tfIe;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfRazao_social;
    // End of variables declaration//GEN-END:variables
}
