/*
 * CadastroFuncionario.java
 *
 * Criado em 10 de Maio de 2005, 15:49
 */
package siscorpi.gui;
import  siscorpi.util.*;
import  javax.swing.*;
import  java.sql.*;
import  siscorpi.funcionario.*;
import  siscorpi.pedido.*;
import  java.text.DecimalFormat;
/**
 * A classe CadastroFuncionario é responsável pela manutenção da base de dados
 * do funcionário 
 *
 * @author Sérgio Leite Bruno
 * @version 1.0
 */
public class CadastroFuncionario extends java.awt.Frame {
    private Pedido fachada;
    private Funcionario funcionarioSelecionado;
    private static final String mascara = "###,###,##0.00";
    ClasseRemoveCaracteres cRemoveCaracteres = new ClasseRemoveCaracteres();
    ClasseMascaraCnpjCPF   cMascaraCnpjCPF   = new ClasseMascaraCnpjCPF();  
    /**
    * Realiza alteração do registro em um banco de dados SQL
    */    
    public CadastroFuncionario() {
        try {
            this.fachada = new Pedido();
            initComponents(); 
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tfIdentidade = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfComissao = new JFormattedTextField(new DecimalFormat(mascara));

        setLayout(null);

        setResizable(false);
        setTitle("SisCorpI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(134, 40));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Cadastro de Funcion\u00e1rios");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 540, 30);

        jPanel3.setBorder(new javax.swing.border.EtchedBorder());
        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.setPreferredSize(new java.awt.Dimension(75, 26));
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jPanel3.add(btGravar);

        btExcluir.setMnemonic('x');
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(75, 26));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jPanel3.add(btExcluir);

        btPesquisar.setMnemonic('P');
        btPesquisar.setText("Pesquisar");
        btPesquisar.setPreferredSize(new java.awt.Dimension(102, 26));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jPanel3.add(btPesquisar);

        btCancelar.setMnemonic('C');
        btCancelar.setText("Cancelar");
        btCancelar.setPreferredSize(new java.awt.Dimension(85, 26));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel3.add(btCancelar);

        btSair.setMnemonic('r');
        btSair.setText("Sair");
        btSair.setPreferredSize(new java.awt.Dimension(60, 26));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel3.add(btSair);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 110, 540, 40);

        jLabel2.setText("C\u00f3digo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 50, 20);

        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFocusLost(evt);
            }
        });

        jPanel1.add(tfCodigo);
        tfCodigo.setBounds(90, 40, 60, 19);

        jLabel3.setText("CPF:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 40, 40, 20);

        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCpfFocusLost(evt);
            }
        });

        jPanel1.add(tfCpf);
        tfCpf.setBounds(200, 40, 130, 21);

        jLabel4.setText("RG:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 40, 30, 20);

        tfIdentidade.setName("tfIe");
        jPanel1.add(tfIdentidade);
        tfIdentidade.setBounds(380, 40, 140, 19);

        tfNome.setName("tfRazao_social");
        jPanel1.add(tfNome);
        tfNome.setBounds(90, 70, 240, 19);

        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 70, 80, 20);

        jLabel6.setText("Cimiss\u00e3o:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 70, 60, 20);

        tfComissao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfComissao.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        tfComissao.setValue(0);
        jPanel1.add(tfComissao);
        tfComissao.setBounds(400, 70, 120, 21);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 150);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    /**
    * Ao perder o foco o sistema verifica se existe um cadastro com este código 
    * caso exista mostra os dados caso não inicia o cadastro
    * 
    */    
    private void tfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusLost
        // TODO add your handling code here:
        String codigo = tfCodigo.getText();
        if (codigo.equals("")) {
            resetFuncionario();
        } else {
            try {
                this.funcionarioSelecionado = fachada.procurarFuncionario(codigo);
                atualizaCampos();
            } catch(FuncionarioNaoEncontradoException ex){
                resetFuncionario();
                tfCodigo.setText(codigo);
            } catch(RepositorioException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
                JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfCodigoFocusLost
    void resetFuncionario() {
        funcionarioSelecionado = null;
        tfCodigo.setText("");
        tfNome.setText("");
        tfIdentidade.setText("");
        tfCpf.setText("");
        tfComissao.setValue(0);
    }
    /**
    * Atualiza os dados na tela do registro em um banco de dados SQL
    * 
    */    
    private void atualizaCampos()
    {
        if (funcionarioSelecionado != null) {
            tfCodigo.setText(funcionarioSelecionado.getCodigo());
            tfNome.setText(funcionarioSelecionado.getNome());
            tfIdentidade.setText(funcionarioSelecionado.getIdentidade());
            tfCpf.setText( cMascaraCnpjCPF.MascaraCnpjCPF( funcionarioSelecionado.getCpf() ) );
            tfComissao.setValue( funcionarioSelecionado.getComissao() );
        }
    } 
    /**
    * Fechar a tela de cadastro
    * 
    */    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed
  /**
  * Limpar os componentes da tela
  * 
  */    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        resetFuncionario();
        tfCodigo.requestFocus();
    }//GEN-LAST:event_btCancelarActionPerformed
    /**
    * Realiza consulta em um banco de dados SQL
    * 
    */    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        tfCodigo.requestFocus();
        PesqQuery pesq = new PesqQuery(3,
        "SELECT Codigo,Cpf,Identidade,Nome FROM funcionario where ",
        new String [] {"Código","CPF","RG","Nome"},
        new String [] {"Codigo","cpf","Identidade","Nome"},2,
        new java.awt.Frame(), true);
	pesq.setVisible(true);
        if ( pesq.getReturnStatus() == 1 )
        {
            tfCodigo.setText(pesq.toString());
            tfNome.requestFocus();
        }    
        pesq = null;
    }//GEN-LAST:event_btPesquisarActionPerformed
  /**
  * Ao perder o foco o sistema verifica a consistência do CPF 
  * 
  */    
    private void tfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusLost
        // TODO add your handling code here:
        String wVal;
        wVal = tfCpf.getText().trim();
        ClasseValidaCpf cValidaCpf = new ClasseValidaCpf();
        if ( ! cValidaCpf.ValidaCpf( tfCpf.getText() ) )
        {    
                JOptionPane.showMessageDialog( null, "CPF informado inválido ",
                "SisCorpI - Informação",
                JOptionPane.INFORMATION_MESSAGE );
                //tfCnpj_cpf.requestFocus();
        }
        cValidaCpf = null;
        tfCpf.setText( cMascaraCnpjCPF.MascaraCnpjCPF( tfCpf.getText() ) );
    }//GEN-LAST:event_tfCpfFocusLost
    /**
    * Limpar a máscara do CPF
    * 
    */    
    private void tfCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusGained
        // TODO add your handling code here:
        tfCpf.setText( cRemoveCaracteres.RemoveCaracteres( new String("./-"), tfCpf.getText() ) );
    }//GEN-LAST:event_tfCpfFocusGained
    /**
    * Realizar exclusão em um banco de dados SQL
    * 
    */    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        String codigo = tfCodigo.getText();
        try {
            fachada.removerFuncionario(codigo);
            resetFuncionario();
            JOptionPane.showMessageDialog(null,"Funcionário excluído com êxito...",
            "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
        } catch(FuncionarioNaoEncontradoException ex){
            resetFuncionario();
            tfCodigo.setText(codigo);
        } catch(RepositorioException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed
    /**
    * Realiza alteração ou inclusão do registro em um banco de dados SQL
    * 
    */    
    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        try {
            if (criaFuncionario()) {
                fachada.cadastrarFuncionario(funcionarioSelecionado);
                JOptionPane.showMessageDialog(null,"Gravação realizada com êxito...",
                "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(FuncionarioNaoEncontradoException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } catch(RepositorioException ex){ 
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btGravarActionPerformed
    /**
    * Inicia os componentes sem conteúdo na tela de cadastro
    * 
    */    
    private boolean criaFuncionario() {
        boolean resposta  = false;
        String codigo     = tfCodigo.getText();
        String nome       = tfNome.getText();
        String identidade = tfIdentidade.getText();
        String cpf        = cRemoveCaracteres.RemoveCaracteres(new String(
                            "./-"),tfCpf.getText());
        String wxv        = ""+tfComissao.getValue();
        double  comissao  = Double.parseDouble(wxv);
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o código do funcionário","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (nome.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o nome do funcionário","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (funcionarioSelecionado == null) {
            funcionarioSelecionado = new Funcionario(codigo,nome,identidade,cpf,comissao);
            resposta = true;
        } else {
            funcionarioSelecionado.setNome(nome);
            funcionarioSelecionado.setIdentidade(identidade);
            funcionarioSelecionado.setCpf(cpf);
            funcionarioSelecionado.setComissao(comissao);
            resposta = true;
        }
        return resposta;
    }
    /** Sair do form */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
         setVisible(false);
    }//GEN-LAST:event_exitForm
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JFormattedTextField tfComissao;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfIdentidade;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    
}
