/*
 * CadastroProduto.java
 *
 * Criado em 10 de Maio de 2005, 17:06
 */
package siscorpi.gui;
import  siscorpi.util.*;
import  javax.swing.*;
import  java.sql.*;
import  siscorpi.produto.*;
import  siscorpi.pedido.*;
import  java.text.DecimalFormat;

/**
 * A classe CadastroProduto é responsável pela manutenção da base de dados
 * do produto 
 *
 * @author Sérgio Leite Bruno
 * @version 1.0
 */
public class CadastroProduto extends java.awt.Frame {
    private Pedido fachada;
    private Produto produtoSelecionado;
    private static final String mascara = "###,###,##0.00";
    /**
    * Realiza alteração do registro em um banco de dados SQL
    */    
    public CadastroProduto() {
        try {
            this.fachada = new Pedido();
            initComponents(); 
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfUnidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCod_barras = new javax.swing.JTextField();
        tfPreco_venda = new JFormattedTextField(new DecimalFormat(mascara));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setResizable(false);
        setTitle("SisCorpI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setText("C\u00f3digo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 50, 20);

        tfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFocusLost(evt);
            }
        });

        jPanel1.add(tfCodigo);
        tfCodigo.setBounds(90, 10, 70, 19);

        jLabel3.setText("Descri\u00e7\u00e3o:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 10, 70, 20);

        jPanel1.add(tfDescricao);
        tfDescricao.setBounds(240, 10, 270, 19);

        jLabel4.setText("P\u00e7o. venda:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 40, 70, 20);

        jLabel5.setText("Unidade:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 40, 50, 20);

        jPanel1.add(tfUnidade);
        tfUnidade.setBounds(240, 40, 70, 19);

        jLabel6.setText("C\u00f3d. Barra:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 40, 70, 20);

        jPanel1.add(tfCod_barras);
        tfCod_barras.setBounds(400, 40, 110, 19);

        tfPreco_venda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPreco_venda.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        tfPreco_venda.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11));
        tfPreco_venda.setValue(0);
        jPanel1.add(tfPreco_venda);
        tfPreco_venda.setBounds(90, 40, 70, 20);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Cadastro de Produtos");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(new javax.swing.border.EtchedBorder());
        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.setPreferredSize(new java.awt.Dimension(75, 26));
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jPanel3.add(btGravar);

        btExcluir.setMnemonic('x');
        btExcluir.setText("Excluir");
        btExcluir.setPreferredSize(new java.awt.Dimension(75, 26));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jPanel3.add(btExcluir);

        btPesquisar.setMnemonic('P');
        btPesquisar.setText("Pesquisar");
        btPesquisar.setPreferredSize(new java.awt.Dimension(102, 26));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jPanel3.add(btPesquisar);

        btCancelar.setMnemonic('C');
        btCancelar.setText("Cancelar");
        btCancelar.setPreferredSize(new java.awt.Dimension(85, 26));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel3.add(btCancelar);

        btSair.setMnemonic('r');
        btSair.setText("Sair");
        btSair.setPreferredSize(new java.awt.Dimension(60, 26));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel3.add(btSair);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
  /**
  * Realiza alteração ou inclusão do registro em um banco de dados SQL
  * 
  */    
    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        try {
            if (criaProduto()) {
                fachada.cadastrarProduto(produtoSelecionado);
                JOptionPane.showMessageDialog(null,"Gravação realizada com êxito...",
                "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(ProdutoNaoEncontradoException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } catch(RepositorioException ex){ 
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btGravarActionPerformed
    private boolean criaProduto() {
        boolean resposta  = false;
        String codigo     = tfCodigo.getText();
        String descricao  = tfDescricao.getText();
        String unidade    = tfUnidade.getText();
        String cod_barras = tfCod_barras.getText();
        String wxv        = ""+tfPreco_venda.getValue();
        double  preco_venda  = Double.parseDouble(wxv);
        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o código do produto","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (descricao.equals("")) {
            JOptionPane.showMessageDialog(null,"Digite o descricao do produto","SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } else if (produtoSelecionado == null) {
            produtoSelecionado = new Produto(codigo,descricao,unidade,cod_barras,preco_venda);
            resposta = true;
        } else {
            produtoSelecionado.setDescricao(descricao);
            produtoSelecionado.setUnidade(unidade);
            produtoSelecionado.setCod_barras(cod_barras);
            produtoSelecionado.setPreco_venda(preco_venda);
            resposta = true;
        }
        return resposta;
    }
    /**
    * Realizar exclusão em um banco de dados SQL
    * 
    */    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        String codigo = tfCodigo.getText();
        try {
            fachada.removerProduto(codigo);
            resetProduto();
            JOptionPane.showMessageDialog(null,"Produto excluído com êxito...",
            "SisCorpI - Atenção",JOptionPane.INFORMATION_MESSAGE);
        } catch(ProdutoNaoEncontradoException ex){
            resetProduto();
            tfCodigo.setText(codigo);
        } catch(RepositorioException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed
    /**
    * Inicia os componentes sem conteúdo na tela de cadastro
    * 
    */    
    void resetProduto() {
        produtoSelecionado = null;
        tfCodigo.setText("");
        tfDescricao.setText("");
        tfUnidade.setText("");
        tfCod_barras.setText("");
        tfPreco_venda.setValue(0);
    }
    /**
    * Realiza consulta em um banco de dados SQL
    * 
    */    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        tfCodigo.requestFocus();
        PesqQuery pesq = new PesqQuery(4, 
        "SELECT Codigo,Cod_barras,descricao,unidade FROM produto where ",
        new String [] {"Código","Cód. Barra","Descrição","Unidade"},
        new String [] {"Codigo","Cod_barras","descricao","Unidade"},2,
        new java.awt.Frame(), true);
	pesq.setVisible(true);
        if ( pesq.getReturnStatus() == 1 )
        {
            tfCodigo.setText(pesq.toString());
            tfDescricao.requestFocus();
        }    
        pesq = null;
    }//GEN-LAST:event_btPesquisarActionPerformed
    /**
    * Limpar os componentes da tela
    * 
    */    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        resetProduto();
        tfCodigo.requestFocus();
    }//GEN-LAST:event_btCancelarActionPerformed
    /**
    * Fechar a tela de cadastro
    * 
    */    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed
    /**
    * Ao perder o foco o sistema verifica se existe um cadastro com este código 
    * caso exista mostra os dados caso não inicia o cadastro
    * 
    */    
    private void tfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusLost
        // TODO add your handling code here:
        String codigo = tfCodigo.getText();
        if (codigo.equals("")) {
            resetProduto();
        } else {
            try {
                this.produtoSelecionado = fachada.procurarProduto(codigo);
                atualizaCampos();
            } catch(ProdutoNaoEncontradoException ex){
                resetProduto();
                tfCodigo.setText(codigo);
            } catch(RepositorioException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
                JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfCodigoFocusLost
    
    /** Sair da aplicação */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
    }//GEN-LAST:event_exitForm
    /**
    * Atualiza os dados na tela do registro em um banco de dados SQL
    * 
    */    
    private void atualizaCampos()
    {
        if (produtoSelecionado != null) {
            tfCodigo.setText(produtoSelecionado.getCodigo());
            tfDescricao.setText(produtoSelecionado.getDescricao());
            tfUnidade.setText(produtoSelecionado.getUnidade());
            tfCod_barras.setText( produtoSelecionado.getCod_barras() );
            tfPreco_venda.setValue( produtoSelecionado.getPreco_venda() );
        }
    } 
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfCod_barras;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JFormattedTextField tfPreco_venda;
    private javax.swing.JTextField tfUnidade;
    // End of variables declaration//GEN-END:variables
    
}
