/*
 * Consultar.java
 *
 * Criado em 10 de Maio de 2005, 23:18
 */
package siscorpi.gui;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.text.DecimalFormat;
import siscorpi.pedido.Pedido;
import siscorpi.util.*;
/**
 * A classe Consultar preenche um JTable com uma consulta SQL, genérica para 
 * qualquer tabela
 *
 * @author Sérgio Leite Bruno
 * @version 1.0
 */
public class Consultar extends java.awt.Frame {
    String listaSQL, TituloConsulta;
    String camposTabela[], nome_CamposTabela[];
    int fachadaSelecionada;
    private Pedido fachada;
    /** Criação do form Consultar */
    public Consultar(int wFachadaSelecionada, String wListaSQL,String wCamposTabela[], String wNome_CamposTabela[],String wTituloConsulta)
    {
        try {
            this.fachada = new Pedido();
            initComponents();
            listaSQL          = wListaSQL;
            camposTabela      = wCamposTabela;
            nome_CamposTabela = wNome_CamposTabela;
            TituloConsulta = wTituloConsulta;
            jlTitulo.setText(TituloConsulta);
            fachadaSelecionada = wFachadaSelecionada;
            displayResultSet();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();

        setResizable(false);
        setTitle("SisCorpI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTabela.setPreferredSize(new java.awt.Dimension(600, 400));
        jScrollPane1.setViewportView(jtTabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 590, 420);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jlTitulo.setForeground(new java.awt.Color(51, 51, 255));
        jlTitulo.setText("Consulta");
        jPanel2.add(jlTitulo);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(new javax.swing.border.EtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(64, 40));
        btSair.setMnemonic('r');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel3.add(btSair);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    /**
     * Fecha a tela de consulta
     */
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btSairActionPerformed
   /**
    * Conecta com o banco e abre a tabela especificada anteriormente
    */
  /**
  * Vai preenchendo o JTable com os itens de um banco de dados SQL
  * 
  * @param rs do tipo ResultSet que aponta para a posição do registro na 
  * tabela
  */    
   private void displayResultSet()
   {
      Vector columnHeads = new Vector();
      Vector rows        = new Vector();
      try {
        switch( fachadaSelecionada ) {
        case 1:
            rows = fachada.listarMvPedido(listaSQL);
            break;
        case 2:
            rows = fachada.listarCliente(listaSQL);
            break;
        case 3:
            rows = fachada.listarFuncionario(listaSQL);
            break;
        case 4:
            rows = fachada.listarProduto(listaSQL);
            break;
        case 5:
            rows = fachada.listarUsuario(listaSQL);
            break;
        }
        boolean[] editavel = new boolean[camposTabela.length];
        for ( int i = 0; i < camposTabela.length; ++i ) 
        {    
            columnHeads.addElement(camposTabela[i]);
            editavel[i] = false;
        }    
        final boolean[] EDIT_COL = editavel;
        jtTabela.setModel(new javax.swing.table.DefaultTableModel( rows, columnHeads ) 
        { boolean[] canEdit = EDIT_COL ;             
           public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit [columnIndex]; }
        }
        );
        validate();
      } catch(RepositorioException ex){ 
            JOptionPane.showMessageDialog(null,ex.getMessage(),"SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
      }
   }
    /** Fecha a tela de consulta */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar(fachadaSelecionada,listaSQL,camposTabela,nome_CamposTabela,TituloConsulta).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables
}
