/*
 * LoginUsuario.java
 *
 * Created on 10 de Setembro de 2005, 22:52
 */

package siscorpi.gui;
import  siscorpi.pedido.*;
import  javax.swing.*;
import  siscorpi.usuario.*;
import  siscorpi.util.*;
/**
 *
 * @author  sergio
 */
public class LoginUsuario extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    private Pedido fachada;
    private Usuario usuarioSelecionado;
    private int nTentativas = 0;
    
    /** Creates new form LoginUsuario */
    public LoginUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            this.fachada = new Pedido();
            initComponents(); 
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("SisCorpI");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonPanel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Icone_6.gif")));
        buttonPanel.add(jLabel1);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setText("Login:           ");
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 14));
        jPanel1.add(jLabel2);

        tfLogin.setPreferredSize(new java.awt.Dimension(90, 19));
        jPanel1.add(tfLogin);

        jLabel3.setText("Senha:");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 14));
        jLabel3.setRequestFocusEnabled(false);
        jPanel1.add(jLabel3);

        pfSenha.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11));
        pfSenha.setMinimumSize(new java.awt.Dimension(90, 19));
        pfSenha.setPreferredSize(new java.awt.Dimension(90, 19));
        jPanel1.add(pfSenha);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jLabel4.setText("Bem vindo ao sistema");
        jPanel2.add(jLabel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String login = tfLogin.getText();
        if (login.equals("")) {
            JOptionPane.showMessageDialog(null,"É necesário informar o login de usuário",
            "SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } 
        else if (pfSenha.equals("")) {
            JOptionPane.showMessageDialog(null,"É necesário informar a senha",
            "SisCorpI - Atenção",
            JOptionPane.WARNING_MESSAGE);
        } 
        else {
            try {
                usuarioSelecionado = fachada.procurarUsuario(login);
                if ( verificaSenha() ) {
                    doClose(RET_OK);
                }
                else {
                    ++nTentativas;
                    if ( nTentativas >= 3 ) {
                        JOptionPane.showMessageDialog(null,
                        "Limite de tentativas excedido, o sistema será encerrado",
                        "SisCorpI - Atenção",JOptionPane.WARNING_MESSAGE);
                        System.exit(0);
                    }
                }
            } catch(UsuarioNaoEncontradoException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage(),
                "SisCorpI - Atenção",JOptionPane.WARNING_MESSAGE);
                tfLogin.setText(login);
                tfLogin.requestFocus();
            } catch(RepositorioException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage(),
                "SisCorpI - Atenção",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private boolean verificaSenha() {
        boolean resposta = false;
        if (usuarioSelecionado != null) {
            String xlogin = usuarioSelecionado.getLogin();
            String xsenha = usuarioSelecionado.getSenha();
            if ( ! xlogin.equals(tfLogin.getText()) ) {
                JOptionPane.showMessageDialog(null,"Usuário não encontrado !",                
                "SisCorpI - Atenção",JOptionPane.WARNING_MESSAGE);
                tfLogin.requestFocus();
            }
            else if ( ! xsenha.equals(pfSenha.getText()) ) {
                JOptionPane.showMessageDialog(null,"Senha inválida !",                
                "SisCorpI - Atenção",JOptionPane.WARNING_MESSAGE);
                pfSenha.requestFocus();
            }           
            else { resposta = true; }
        }
        return resposta;
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    public String toString() { return tfLogin.getText(); }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuario(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfLogin;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
